language: java

matrix:
  include:
    - os: linux
      jdk: openjdk10
      env:
        - INTEGRATION_TEST="integration"
        - JDK=openjdk10
        - OS=linux
      sudo: true
      dist: xenial
      services:
        - docker
      addons:
        sonarqube:
          organization: nlesc
      before_install:
        - docker-compose --version
      install:
        - ./gradlew assemble
      script:
        - ./gradlew check
      after_script:
        - ./gradlew jacocoIntegrationTestReport
        - bash <(curl -s https://codecov.io/bash) -e JDK,OS -F unit -f build/reports/jacoco/test/jacocoTestReport.xml;
        - bash <(curl -s https://codecov.io/bash) -e JDK,OS -F integration -f build/reports/jacoco/jacocoIntegrationTestReport/jacocoIntegrationTestReport.xml;
        - sonar-scanner -Dsonar.login=$SONAR_TOKEN;

    - os: osx
      env:
        - INTEGRATION_TEST="livelocal"
        - JDK=openjdk10
        - OS=osx
      osx_image: xcode9.4
      script:
        - ./gradlew test
      after_script:
       -  ./gradlew jacocoTestReport
       - bash <(curl -s https://codecov.io/bash) -e JDK,OS -F unit -f build/reports/jacoco/test/jacocoTestReport.xml;
  fast_finish: true


install:
  - ./gradlew assemble

