# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install wheel
      run: pip install -U wheel pip
    - name: Install moto
      run: pip install moto[server]
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Build
      run: ./gradlew assemble
    - name: Check
      run: ./gradlew check jacocoIntegrationTestReport jacocoTestReport
    - name: SonarCloud analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew sonarqube
    - name: Unit coverage reports
      uses: codecov/codecov-action@v1
      with:
        files: build/reports/jacoco/test/jacocoTestReport.xml
        flags: unit,jdk11,${{ runner.os }}
    - name: Integration coverage reports
      uses: codecov/codecov-action@v1
      with:
        files: build/reports/jacoco/jacocoIntegrationTestReport/jacocoIntegrationTestReport.xml
        flags: integration,jdk11,${{ runner.os }}
  osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Build
      run: ./gradlew assemble
    - name: Check
      run: ./gradlew test jacocoTestReport
    - name: Unit coverage reports
      uses: codecov/codecov-action@v1
      with:
        files: build/reports/jacoco/test/jacocoTestReport.xml
        flags: unit,jdk11,${{ runner.os }}
